version: "3"
services:
  web_server:
    privileged: true
    build:
       context: ./
       dockerfile: web.dockerfile
    container_name: centos-server
    volumes:
      - ./:/var/www/html
    cap_add:
      - SYS_ADMIN
    ports:
      - 80:80
